workspace(name = "llvm_x_toolchain_test")

local_repository(
    name = "llvm_x_toolchain",
    path = "..",
)

load("@llvm_x_toolchain//bazel:repositories.bzl", "llvm_x_toolchain_repositories")

llvm_x_toolchain_repositories()

load("@llvm_x_toolchain//bazel:llvm_x_toolchain_init.bzl", "llvm_x_toolchain_init")

llvm_x_toolchain_init()

# Dependencies of the tests repo
load("//bazel:repositories.bzl", "llvm_x_toolchain_test_repositories")

llvm_x_toolchain_test_repositories()

load("//bazel:llvm_x_toolchain_test_init.bzl", "llvm_x_toolchain_test_init")

llvm_x_toolchain_test_init()

# Setup toolchains
load("@llvm_x_toolchain//toolchain:rules.bzl", "llvm_toolchain")

llvm_toolchain(
    name = "llvm_toolchain",
    stdlib = {
        "": "stdc++",
    },
)

load("@llvm_toolchain//:toolchains.bzl", "llvm_register_toolchains")

llvm_register_toolchains()

llvm_toolchain(
    name = "llvm_toolchain_for_asan",
    extra_compiler_deps = {
        "": [
            "@llvm_x_toolchain_test//bazel/sanitizers:asan_deps",
        ],
    },
    stdlib = {
        "": "stdc++",
    },
)

llvm_toolchain(
    name = "orin_cross_toolchain",
    sysroot = {
        "linux-aarch64": "/l4t/targetfs",
    },
)

llvm_toolchain(
    name = "j5_cross_toolchain",
    sysroot = {
        "linux-aarch64": "@chromium_sysroot_linux_aarch64//:sysroot",
    },
)
