package(default_visibility = ["//visibility:public"])

constraint_setting(name = "soctype")

constraint_value(
    name = "xavier",
    constraint_setting = ":soctype",
)

constraint_value(
    name = "j5",
    constraint_setting = ":soctype",
)
