package(default_visibility = ["//visibility:public"])

filegroup(
    name = "asan_deps",
    srcs = glob(
        [
            "asan/ignorelist.txt",
        ],
        allow_empty = True,
    ),
)
