# This BUILD file exports the templates and static files needed for dynamic toolchain configuration.
# See internal/configure.bzl for how they are used.
package(default_visibility = ["//visibility:public"])

exports_files(
    glob(
        ["*"],
        exclude = ["BUILD"],
    ),
)
